export const SEARCH_REPOS_REQUEST = 'SEARCH_REPOS_REQUEST';
export const SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS';
export const SEARCH_REPOS_FAIL = 'SEARCH_REPOS_FAIL';

// OR
export enum ReposActionType {
  SEARCH_REPOS_REQUEST = 'SEARCH_REPOS_REQUEST',
  SEARCH_REPOS_SUCCESS = 'SEARCH_REPOS_SUCCESS',
  SEARCH_REPOS_FAIL = 'SEARCH_REPOS_ENUM',
}
